### ISSUE TITLE
Initializer element is not constant

### ISSUE THREAD

**Issue by lhbj06** [chinook/VolantC11#2]
`source/main.c:80:2: error: initializer element is not constant`
 `SW1, SW2, SW3, SW4, SW5, SW6, SW7, SW8, SW9, SW10, SW11, SW12`

`source/main.c:80:2: error: (near initialization for 'swi_to_sw[0]')`
`source/main.c:80:2: error: initializer element is not constant`

Honestly, idk wtf is this

**Comment by FredericChasse** [comment]
You're trying to initialize a global variable with values from registers (PORTEbits.RE0, ..., PORTEbits.RE15)

Either move the declaration of swi_to_sw to a function, or keep the declaration global and move the the init values to main()

**Comment by nhl-001** [comment]
Fixed in b7e67c2
